name: flutter_project_getx
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_fonts: ^6.2.1
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  shared_preferences: ^2.5.3
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  flutter_3d_controller: ^2.2.0
  flutter_neumorphic:
    git:
      url: https://github.com/den0206/Flutter-Neumorphic.git
      ref: feature/remoce_accentcolor
  panorama: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0    

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/3d/car/
    - assets/3d/
    - assets/car_item_icon/







